const codePromoController = require("../Controllers/codePromo.controller")
const express = require ("express")
const { AuthorizationUser } = require("../middleware/auth/auth")
const router =  express.Router() 
router.post("/add",codePromoController.add) 
router.post("/addmanual", AuthorizationUser,codePromoController.addmanual)
router.delete("/delete/:id" ,AuthorizationUser,codePromoController.delete)
router.get("/findAll",codePromoController.findAll) 
router.get("/findOne/:id", codePromoController.findOne)
router.get("/findByuser/:id", codePromoController.findByuser)
router.get("/findBypartenaire/:id", codePromoController.findBypartenaire)
router.put("/update/:id" ,AuthorizationUser, codePromoController.update)
router.get("/findBycode", codePromoController.findBycode)
module.exports = router